<a href="https://colab.research.google.com/github/241801506/MACHINE-LEARNING-USING-AI/blob/main/copy_of_numpy_and_pandas_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import sys
s=range(1000)
print("size of each element of list in bytes:",sys.getsizeof(s))
print("size of the whole list in bytes:",sys.getsizeof(s)*len(s))
D=np.arange(1000)
print("size of the each elementof the numpy array in bytes:",D.itemsize)
print("size of the whole numpy array in bytes :",D.size*D.itemsize)

size of each element of list in bytes: 48
size of the whole list in bytes: 48000
size of the each elementof the numpy array in bytes: 8
size of the whole numpy array in bytes : 8000


In [ ]:
arr=np.array(42)
print(arr)

42


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
