In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
arr = np.array(42)
print(arr)

42


In [3]:
identity_matrix = np.eye(3)
print(identity_matrix)
identity_matrix = np.eye(4)
print("\n",identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
import numpy as np

a = np.array([1., 2., 3., 4.])
b = np.array([5., 6., 7., 8.])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [5]:
arr =np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
import sys
S=range(1000)
print("size of each element of list in bytes:",sys.getsizeof(S))
print("size of the whole list in bytes:",sys.getsizeof(S)*len(S))
D=np.arange(1000)
print("size of the each element of the Numpy array in bytes:",D.itemsize)
print("size of the whole Numpy array in  bytes:",D.size*D.itemsize)


size of each element of list in bytes: 48
size of the whole list in bytes: 48000
size of the each element of the Numpy array in bytes: 8
size of the whole Numpy array in  bytes: 8000


In [9]:
zeros_arr=np.zeros((5,2))
eros_arr=np.zeros(5)
print(zeros_arr)

zeros_arr=np.zeros((2,3))
print(zeros_arr)

print("Data type of the array:",zeros_arr.dtype)

zeros_arr_int=np.zeros((3,3),dtype=np.int16)
print("\nArray of zeros with integer elements: \n",zeros_arr_int)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
Data type of the array: float64

Array of zeros with integer elements: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
ones_arr=np.ones(6)
print(ones_arr)


[1. 1. 1. 1. 1. 1.]


In [11]:
empty_arr=np.empty((3,2))
print(empty_arr)

print("\nData type of the array:",empty_arr.dtype)


[[1. 1.]
 [1. 1.]
 [1. 1.]]

Data type of the array: float64


In [12]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [13]:
arr=np.array([1,2,3])
print("Before converting:",arr,arr.dtype)

new_arr=arr.astype('f')
print("After converting:",new_arr,new_arr.dtype)

Before converting: [1 2 3] int64
After converting: [1. 2. 3.] float32


In [14]:
arr1=np.arange(10)
arr2=np.random.randn(10)

print("array 1\n",arr1,arr1.dtype)
print("Array 2\n",arr2,arr2.dtype)

new_arr=arr1.astype(arr2.dtype)

print("New Array  \n",new_arr,new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2
 [ 0.33638275 -0.239503    1.51352256  0.21462279 -0.94281131 -1.64325862
 -1.8375839  -1.49007063 -0.51054927 -1.67366439] float64
New Array  
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
